### ISSUE TITLE
WAPI is not defined

### ISSUE THREAD

**Issue by jambazishvili** [wppconnect-team/wppconnect-server#1863] opened 2024-05-22 04:02 UTC
## Description
`error: 2024-05-21T12:03:50.660Z WAPI is not defined - Error: WAPI is not defined`

## Environment

- **Wppconnect-server version(s):** 2.4.4
- **Browser:** Chromium 119.0.6045.159 Alpine Linux
- **OS:** Ubuntu 22 / Docker container
- **Node version:** v20.13.1
- **WhatsApp version:** 2.24.9.78
- **MultiDevice (BETA):** yes
- **config.json:**
```
import { ServerOptions } from './types/ServerOptions';

export default {
  secretKey: 'THISISMYSECURETOKEN',
  host: 'http://localhost',
  port: '21465',
  deviceName: 'Desktop',
  poweredBy: 'WPPConnect-Server',
  startAllSession: true,
  tokenStoreType: 'file',
  maxListeners: 1000,
  customUserDataDir: './userDataDir/',
  webhook: {
    url: 'http://event_hook***',
    autoDownload: true,
    uploadS3: false,
    readMessage: false,
    allUnreadOnStart: false,
    listenAcks: true,
    onPresenceChanged: false,
    onParticipantsChanged: false,
    onReactionMessage: true,
    onPollResponse: false,
    onRevokedMessage: true,
    onLabelUpdated: false,
    onSelfMessage: true,
    ignore: ['status@broadcast'],
  },
  websocket: {
    autoDownload: false,
    uploadS3: false,
  },
  chatwoot: {
    sendQrCode: true,
    sendStatus: true,
  },
  archive: {
    enable: false,
    waitTime: 10,
    daysToArchive: 45,
  },
  log: {
    level: 'silly', // Before open a issue, change level to silly and retry a action
    logger: ['console', 'file'],
  },
  createOptions: {
    browserArgs: [
      '--disable-web-security',
      '--no-sandbox',
      '--disable-web-security',
      '--aggressive-cache-discard',
      '--disable-cache',
      '--disable-application-cache',
      '--disable-offline-load-stale-cache',
      '--disk-cache-size=0',
      '--disable-background-networking',
      '--disable-default-apps',
      '--disable-extensions',
      '--disable-sync',
      '--disable-translate',
      '--hide-scrollbars',
      '--metrics-recording-only',
      '--mute-audio',
      '--no-first-run',
      '--safebrowsing-disable-auto-update',
      '--ignore-certificate-errors',
      '--ignore-ssl-errors',
      '--ignore-certificate-errors-spki-list',
      '--disable-features=LeakyPeeker',
    ],
    /**
     * Example of configuring the linkPreview generator
     * If you set this to 'null', it will use global servers; however, you have the option to define your own server
     * Clone the repository https://github.com/wppconnect-team/wa-js-api-server and host it on your server with ssl
     *
     * Configure the attribute as follows:
     * linkPreviewApiServers: [ 'https://www.yourserver.com/wa-js-api-server' ]
     */
    linkPreviewApiServers: null,
  },
  mapper: {
    enable: false,
    prefix: 'tagone-',
  },
  db: {
    mongodbDatabase: 'tokens',
    mongodbCollection: '',
    mongodbUser: '',
    mongodbPassword: '',
    mongodbHost: '',
    mongoIsRemote: true,
    mongoURLRemote: '',
    mongodbPort: 27017,
    redisHost: 'localhost',
    redisPort: 6379,
    redisPassword: '',
    redisDb: 0,
    redisPrefix: 'docker',
  },
  aws_s3: {
    region: 'sa-east-1' as any,
    access_key_id: null,
    secret_key: null,
    defaultBucketName: null,
    endpoint: null,
    forcePathStyle: null,
  },
} as unknown as ServerOptions;
```

## Steps to Reproduce
1. Run the wppconnect-server on VM (*GCP*)
2. Start the session
3. Scan the QR code
4. QR code is successfully scanned
5. Connection is initializing, but wppconnect-server logs that WAPI is not found (see the logs) and mobile device does not pairs.

## Log Output

```
info:     [<session_name>:browser] Using browser folder './userDataDir/<session_name>'
info:     [<session_name>:browser] Initializing browser...
http:     [<session_name>:browser] checking headless...
http:     [<session_name>:browser] headless option is active, browser hidden
info:     [<session_name>:client] Initializing...
verbose:  [<session_name>:client] Setting WhatsApp WEB version to 2.2411.x
verbose:  [<session_name>:client] Loading WhatsApp WEB
verbose:  [<session_name>:page] Page loaded
verbose:  [<session_name>:client] Injecting wapi.js
verbose:  [<session_name>:client] WhatsApp WEB loaded
http:     [<session_name>:client] Waiting page load
info:     [<session_name>:session] Session Unpaired
verbose:  [<session_name>:client] wapi.js injected
debug:    [<session_name>:client] Exposing onMessage function
info:     [<session_name>:client] WhatsApp WEB version: 2.2411.2
info:     [<session_name>:client] WA-JS version: 3.2.6
debug:    [<session_name>:client] Exposing onAnyMessage function
debug:    [<session_name>:client] Exposing onAck function
debug:    [<session_name>:client] Exposing onNotificationMessage function
debug:    [<session_name>:client] Exposing onParticipantsChanged function
debug:    [<session_name>:client] Exposing onStateChange function
http:     [<session_name>:client] Checking is logged...
debug:    [<session_name>:client] Exposing onStreamChange function
info:     [<session_name>:client] Auto close configured to 60s
http:     [<session_name>:client] Waiting for QRCode Scan...
info: 2024-05-21T12:03:37.541Z notLogged


debug:    [<session_name>:client] Exposing onIncomingCall function
debug:    [<session_name>:client] Exposing onInterfaceChange function
debug:    [<session_name>:client] Exposing onPresenceChanged function
debug:    [<session_name>:client] Exposing onLiveLocation function
debug:    [<session_name>:client] Exposing onAddedToGroup function
debug:    [<session_name>:client] Exposing onRevokedMessage function
debug:    [<session_name>:client] Exposing onReactionMessage function
debug:    [<session_name>:client] Exposing onPollResponse function
debug:    [<session_name>:client] Exposing onUpdateLabel function
debug:    [<session_name>:client] Exposing onOrderStatusUpdate function
debug:    [<session_name>:client] Emitting onInterfaceChange event (1 registered)
http:     [<session_name>:client] Current state: QR (CONNECTING)
debug:    [<session_name>:client] Emitting onInterfaceChange event (1 registered)
http:     [<session_name>:client] Current state: QR (CONNECTING)
debug:    [<session_name>:client] Emitting onInterfaceChange event (1 registered)
http:     [<session_name>:client] Current state: QR (CONNECTING)
info:     [<session_name>:client] Waiting for QRCode Scan (Attempt 1)...:
<QR_CODE>
http:     [<session_name>:client] Auto close remain: 50s
http:     [<session_name>:client] Checking QRCode status...
http:     [<session_name>:client] Login with success
info: 2024-05-21T12:03:49.391Z qrReadSuccess


info:     [<session_name>:client] Auto close configured to 180s
http:     [<session_name>:client] Checking phone is connected...
verbose:  [<session_name>:page] Page loaded
verbose:  [<session_name>:client] Injecting wapi.js
debug:    [<session_name>:client] Registering onStateChange event
error: 2024-05-21T12:03:50.660Z WAPI is not defined - Error: WAPI is not defined
    at /usr/src/wpp-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:107:31
    at step (/usr/src/wpp-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:49:23)
    at Object.next (/usr/src/wpp-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:30:53)
    at fulfilled (/usr/src/wpp-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:21:58)
JS Stack: ReferenceError: WAPI is not defined
    at pptr:evaluate;%2Fusr%2Fsrc%2Fwpp-server%2Fnode_modules%2F%40wppconnect-team%2Fwppconnect%2Fdist%2Fapi%2Fhelpers%2Fevaluate-and-return.js%3A99%3A56:56:47
    at pptr:evaluate;%2Fusr%2Fsrc%2Fwpp-server%2Fnode_modules%2F%40wppconnect-team%2Fwppconnect%2Fdist%2Fapi%2Fhelpers%2Fevaluate-and-return.js%3A99%3A56:56:77
    at new Promise (<anonymous>)
    at anonymous (pptr:evaluate;%2Fusr%2Fsrc%2Fwpp-server%2Fnode_modules%2F%40wppconnect-team%2Fwppconnect%2Fdist%2Fapi%2Fhelpers%2Fevaluate-and-return.js%3A99%3A56:54:14)
Function: function () { return WAPI.isConnected(); }
debug:    [<session_name>:client] Registering onStateChange event
debug:    [<session_name>:client] Registering onMessage event
debug:    [<session_name>:client] Registering onAnyMessage event
debug:    [<session_name>:client] Registering onIncomingCall event
debug:    [<session_name>:client] Registering onAck event
error: 2024-05-21T12:03:51.216Z WAPI is not defined - Error: WAPI is not defined
    at /usr/src/wpp-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:107:31
    at step (/usr/src/wpp-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:49:23)
    at Object.next (/usr/src/wpp-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:30:53)
    at fulfilled (/usr/src/wpp-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:21:58)
JS Stack: ReferenceError: WAPI is not defined
    at pptr:evaluate;%2Fusr%2Fsrc%2Fwpp-server%2Fnode_modules%2F%40wppconnect-team%2Fwppconnect%2Fdist%2Fapi%2Fhelpers%2Fevaluate-and-return.js%3A99%3A56:56:47
    at pptr:evaluate;%2Fusr%2Fsrc%2Fwpp-server%2Fnode_modules%2F%40wppconnect-team%2Fwppconnect%2Fdist%2Fapi%2Fhelpers%2Fevaluate-and-return.js%3A99%3A56:56:77
    at new Promise (<anonymous>)
    at anonymous (pptr:evaluate;%2Fusr%2Fsrc%2Fwpp-server%2Fnode_modules%2F%40wppconnect-team%2Fwppconnect%2Fdist%2Fapi%2Fhelpers%2Fevaluate-and-return.js%3A99%3A56:54:14)
Function: function () { return WAPI.isConnected(); }
verbose:  [<session_name>:client] wapi.js injected
info:     [<session_name>:client] WhatsApp WEB version: 2.2411.2
info:     [<session_name>:client] WA-JS version: 3.2.6
debug:    [<session_name>:client] Emitting onStateChange event (2 registered)
info: 2024-05-21T12:03:52.109Z State Change UNLAUNCHED: <session_name>
debug:    [<session_name>:client] Emitting onInterfaceChange event (1 registered)
http:     [<session_name>:client] Current state: QR (CONNECTING)
http:     [<session_name>:client] Waiting page load
http:     [<session_name>:client] Checking is logged...
info:     [<session_name>:client] Auto close configured to 60s
http:     [<session_name>:client] Waiting for QRCode Scan...
info: 2024-05-21T12:03:55.272Z notLogged


debug:    [<session_name>:client] Emitting onInterfaceChange event (1 registered)
http:     [<session_name>:client] Current state: QR (CONNECTING)
debug:    [<session_name>:client] Emitting onStateChange event (2 registered)
info: 2024-05-21T12:03:55.469Z State Change OPENING: <session_name>
debug:    [<session_name>:client] Emitting onInterfaceChange event (1 registered)
http:     [<session_name>:client] Current state: QR (CONNECTING)
debug:    [<session_name>:client] Emitting onStateChange event (2 registered)
info: 2024-05-21T12:03:55.846Z State Change PAIRING: <session_name>
debug:    [<session_name>:client] Emitting onInterfaceChange event (1 registered)
http:     [<session_name>:client] Current state: QR (CONNECTING)
debug:    [<session_name>:client] Emitting onStateChange event (2 registered)
info: 2024-05-21T12:03:55.987Z State Change UNPAIRED: <session_name>
info:     [<session_name>:client] Waiting for QRCode Scan (Attempt 1)...:
<QR_CODE>
http:     [<session_name>:client] Auto close remain: 50s
http:     [<session_name>:client] Auto close remain: 40s
http:     [<session_name>:client] Auto close remain: 30s
http:     [<session_name>:client] Auto close remain: 20s
http:     [<session_name>:client] Auto close remain: 10s
```

## Your Code

```
If relevant, paste all of your challenge code in here
```

## Additional context / Screenshot

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by gitdedc** [comment] 2024-05-22 19:28
I found the problem.. investigating the solution

**Comment by gitdedc** [comment] 2024-05-22 19:41
Please, do:

Clear folder userdatadir
Clear folder tokens
Create a new token to session named test (and not <session_name>)
Connect and read qrcode
Wait 5 minutes with server running
Stop and start again

Post here the result.

**Comment by jambazishvili** [comment] 2024-05-23 04:13
> Please, do:
> 
> Clear folder userdatadir Clear folder tokens Create a new token to session named test (and not <session_name>) Connect and read qrcode Wait 5 minutes with server running Stop and start again
> 
> Post here the result.

Hello, thanks for the reply!

Actually the <session_name> is just a placeholder, I've replaced it for the privacy reasons. The real name was like 2 chars followed by 4 digits, like xx1234.

We have tried to clean up the userdatadir & tokens dirs multiple time, but the result is the same, it reports that the wapi js is undefined and this is not the only device foe us - we have several which have the same problem.

In any case, we'll re-tey again based on your instructions & put the logs here.

**Comment by jambazishvili** [comment] 2024-05-23 11:53
> Please, do:
> 
> Clear folder userdatadir Clear folder tokens Create a new token to session named test (and not <session_name>) Connect and read qrcode Wait 5 minutes with server running Stop and start again
> 
> Post here the result.

Hello again, back w/ the results as you've suggested:
1. We've cleared the `userdatadir` & `tokens` folder (*we've run the fresh container actually w/o prior history on the VM*).
2. We've created the session named `test` (*but as noted, our previous session name was also alphanumeric*).
3. We've connected, read the QR code - resulted in the same error.
4. Then we've re-started and attempted again - resulted in the same error.

Here are the logs for more information:
```
yarn run v1.22.19
$ node ./dist/server.js
info: 2024-05-23T07:24:01.658Z Server is running on port: 21465
info: 2024-05-23T07:24:01.663Z  Visit http://localhost:21465/api-docs for Swagger docs
info: 2024-05-23T07:24:01.663Z WPPConnect-Server version: 2.4.4
info:     
  _       ______  ____  ______                            __ 
  | |     / / __ \/ __ \/ ____/___  ____  ____  ___  _____/ /_
  | | /| / / /_/ / /_/ / /   / __ \/ __ \/ __ \/ _ \/ ___/ __/
  | |/ |/ / ____/ ____/ /___/ /_/ / / / / / / /  __/ /__/ /_  
  |__/|__/_/   /_/    \____/\____/_/ /_/_/ /_/\___/\___/\__/
info:     Checking for updates
info:     You're up to date
info:     [test:browser] Using browser folder './userDataDir/test'
info:     [test:browser] Initializing browser...
info:     [test:client] Initializing...
info:     [test:session] Session Unpaired
info:     [test:client] WhatsApp WEB version: 2.2411.2
info:     [test:client] WA-JS version: 3.2.4
info:     [test:client] Auto close configured to 60s
info: 2024-05-23T07:25:40.184Z notLogged


info:     [test:client] Waiting for QRCode Scan (Attempt 1)...:
<QR_CODE>
 {"code":"***,1"}
info: 2024-05-23T07:25:48.789Z qrReadSuccess
info:     [test:client] Auto close configured to 180s
error: 2024-05-23T07:25:50.225Z WAPI is not defined - Error: WAPI is not defined
    at /usr/src/wpp-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:107:31
    at step (/usr/src/wpp-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:49:23)
    at Object.next (/usr/src/wpp-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:30:53)
    at fulfilled (/usr/src/wpp-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:21:58)
JS Stack: ReferenceError: WAPI is not defined
    at pptr:evaluate;%2Fusr%2Fsrc%2Fwpp-server%2Fnode_modules%2F%40wppconnect-team%2Fwppconnect%2Fdist%2Fapi%2Fhelpers%2Fevaluate-and-return.js%3A99%3A56:56:47
    at pptr:evaluate;%2Fusr%2Fsrc%2Fwpp-server%2Fnode_modules%2F%40wppconnect-team%2Fwppconnect%2Fdist%2Fapi%2Fhelpers%2Fevaluate-and-return.js%3A99%3A56:56:77
    at new Promise (<anonymous>)
    at anonymous (pptr:evaluate;%2Fusr%2Fsrc%2Fwpp-server%2Fnode_modules%2F%40wppconnect-team%2Fwppconnect%2Fdist%2Fapi%2Fhelpers%2Fevaluate-and-return.js%3A99%3A56:54:14)
Function: function () { return WAPI.isConnected(); }
error: 2024-05-23T07:25:51.216Z WAPI is not defined - Error: WAPI is not defined
    at /usr/src/wpp-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:107:31
    at step (/usr/src/wpp-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:49:23)
    at Object.next (/usr/src/wpp-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:30:53)
    at fulfilled (/usr/src/wpp-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:21:58)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at process.processImmediate (node:internal/timers:449:9)
JS Stack: ReferenceError: WAPI is not defined
    at pptr:evaluate;%2Fusr%2Fsrc%2Fwpp-server%2Fnode_modules%2F%40wppconnect-team%2Fwppconnect%2Fdist%2Fapi%2Fhelpers%2Fevaluate-and-return.js%3A99%3A56:56:47
    at pptr:evaluate;%2Fusr%2Fsrc%2Fwpp-server%2Fnode_modules%2F%40wppconnect-team%2Fwppconnect%2Fdist%2Fapi%2Fhelpers%2Fevaluate-and-return.js%3A99%3A56:56:77
    at new Promise (<anonymous>)
    at anonymous (pptr:evaluate;%2Fusr%2Fsrc%2Fwpp-server%2Fnode_modules%2F%40wppconnect-team%2Fwppconnect%2Fdist%2Fapi%2Fhelpers%2Fevaluate-and-return.js%3A99%3A56:54:14)
Function: function () { return WAPI.isConnected(); }
info:     [test:client] WhatsApp WEB version: 2.2411.2
info:     [test:client] WA-JS version: 3.2.4
info: 2024-05-23T07:25:53.816Z State Change UNLAUNCHED: test
info: 2024-05-23T07:25:54.014Z State Change OPENING: test
info: 2024-05-23T07:25:54.610Z State Change PAIRING: test
info: 2024-05-23T07:25:54.888Z State Change UNPAIRED: test
info:     [test:client] Waiting for QRCode Scan (Attempt 1)...:
<QR_CODE>
 {"code":"***,1"}
info:     [test:client] Auto close configured to 60s
info: 2024-05-23T07:25:55.830Z notLogged
info:     [test:client] Waiting for QRCode Scan (Attempt 2)...:
<QR_CODE>
 {"code":"***,1"}
info:     [test:client] Closing the page
info: 2024-05-23T07:26:55.852Z autocloseCalled
info: 2024-05-23T07:26:55.931Z browserClose
warn:     [test:client] Failed to authenticate
info: 2024-05-23T07:26:56.131Z qrReadError
error:    [test:client] Auto Close Called

--- container restart ---

yarn run v1.22.19
$ node ./dist/server.js
info: 2024-05-23T07:30:25.031Z Server is running on port: 21465
info: 2024-05-23T07:30:25.037Z  Visit http://localhost:21465/api-docs for Swagger docs
info: 2024-05-23T07:30:25.037Z WPPConnect-Server version: 2.4.4
info:     
  _       ______  ____  ______                            __ 
  | |     / / __ \/ __ \/ ____/___  ____  ____  ___  _____/ /_
  | | /| / / /_/ / /_/ / /   / __ \/ __ \/ __ \/ _ \/ ___/ __/
  | |/ |/ / ____/ ____/ /___/ /_/ / / / / / / /  __/ /__/ /_  
  |__/|__/_/   /_/    \____/\____/_/ /_/_/ /_/\___/\___/\__/
info:     Checking for updates
info:     You're up to date
info:     [test:browser] Using browser folder './userDataDir/test'
info:     [test:browser] Initializing browser...
info:     [test:client] Initializing...
info:     [test:session] Session Unpaired
info:     [test:client] WhatsApp WEB version: 2.2411.2
info:     [test:client] WA-JS version: 3.2.4
info:     [test:client] Auto close configured to 60s
info: 2024-05-23T07:30:40.052Z notLogged
info:     [test:client] Waiting for QRCode Scan (Attempt 1)...:
<QR_CODE>
 {"code":"***,1"}
info:     [test:client] Closing the page
info: 2024-05-23T07:31:40.176Z browserClose
warn:     [test:client] Failed to authenticate
info: 2024-05-23T07:31:40.383Z qrReadError
error:    [test:client] Auto Close Called
error: 2024-05-23T07:31:40.386Z Auto Close Called
info:     [test:browser] Using browser folder './userDataDir/test'
info:     [test:browser] Initializing browser...
info:     [test:client] Initializing...
info:     [test:session] Session Unpaired
info:     [test:client] WhatsApp WEB version: 2.2411.2
info:     [test:client] WA-JS version: 3.2.4
info:     [test:client] Auto close configured to 60s
info: 2024-05-23T07:32:58.825Z notLogged
info:     [test:client] Waiting for QRCode Scan (Attempt 1)...:
<QR_CODE>
 {"code":"***,1"}
info: 2024-05-23T07:33:08.954Z qrReadSuccess
info:     [test:client] Auto close configured to 180s
error: 2024-05-23T07:33:10.985Z WAPI is not defined - Error: WAPI is not defined
    at /usr/src/wpp-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:107:31
    at step (/usr/src/wpp-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:49:23)
    at Object.next (/usr/src/wpp-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:30:53)
    at fulfilled (/usr/src/wpp-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:21:58)
JS Stack: ReferenceError: WAPI is not defined
    at pptr:evaluate;%2Fusr%2Fsrc%2Fwpp-server%2Fnode_modules%2F%40wppconnect-team%2Fwppconnect%2Fdist%2Fapi%2Fhelpers%2Fevaluate-and-return.js%3A99%3A56:56:47
    at pptr:evaluate;%2Fusr%2Fsrc%2Fwpp-server%2Fnode_modules%2F%40wppconnect-team%2Fwppconnect%2Fdist%2Fapi%2Fhelpers%2Fevaluate-and-return.js%3A99%3A56:56:77
    at new Promise (<anonymous>)
    at anonymous (pptr:evaluate;%2Fusr%2Fsrc%2Fwpp-server%2Fnode_modules%2F%40wppconnect-team%2Fwppconnect%2Fdist%2Fapi%2Fhelpers%2Fevaluate-and-return.js%3A99%3A56:54:14)
Function: function () { return WAPI.isConnected(); }
error: 2024-05-23T07:33:11.078Z WAPI is not defined - Error: WAPI is not defined
    at /usr/src/wpp-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:107:31
    at step (/usr/src/wpp-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:49:23)
    at Object.next (/usr/src/wpp-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:30:53)
    at fulfilled (/usr/src/wpp-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:21:58)
JS Stack: ReferenceError: WAPI is not defined
    at pptr:evaluate;%2Fusr%2Fsrc%2Fwpp-server%2Fnode_modules%2F%40wppconnect-team%2Fwppconnect%2Fdist%2Fapi%2Fhelpers%2Fevaluate-and-return.js%3A99%3A56:56:47
    at pptr:evaluate;%2Fusr%2Fsrc%2Fwpp-server%2Fnode_modules%2F%40wppconnect-team%2Fwppconnect%2Fdist%2Fapi%2Fhelpers%2Fevaluate-and-return.js%3A99%3A56:56:77
    at new Promise (<anonymous>)
    at anonymous (pptr:evaluate;%2Fusr%2Fsrc%2Fwpp-server%2Fnode_modules%2F%40wppconnect-team%2Fwppconnect%2Fdist%2Fapi%2Fhelpers%2Fevaluate-and-return.js%3A99%3A56:54:14)
Function: function () { return WAPI.isConnected(); }
info:     [test:client] WhatsApp WEB version: 2.2411.2
info:     [test:client] WA-JS version: 3.2.4
info: 2024-05-23T07:33:14.179Z State Change UNLAUNCHED: test
info: 2024-05-23T07:33:14.377Z State Change OPENING: test
info: 2024-05-23T07:33:14.978Z State Change PAIRING: test
info: 2024-05-23T07:33:15.255Z State Change UNPAIRED: test
info:     [test:client] Waiting for QRCode Scan (Attempt 1)...:
<QR_CODE>
 {"code":"***,1"}
info:     [test:client] Auto close configured to 60s
info: 2024-05-23T07:33:16.198Z notLogged
info:     [test:client] Waiting for QRCode Scan (Attempt 2)...:
<QR_CODE>
 {"code":"***,1"}
info:     [test:client] Closing the page
info: 2024-05-23T07:34:16.215Z autocloseCalled
info: 2024-05-23T07:34:16.226Z browserClose
warn:     [test:client] Failed to authenticate
info: 2024-05-23T07:34:16.588Z qrReadError
error:    [test:client] Auto Close Called
^C
```

**Comment by gitdedc** [comment] 2024-05-23 11:58
Ok.  I can't reproduce the error.  I'm checking

**Comment by gitdedc** [comment] 2024-05-29 19:15
I created a new server using ARM Processor, Ubuntu 22.04, NPM, NVM and Chromium (Chrome too and no problem found).  Node 18.18.0.
No problem found.  I created token, read qrcode, stop server, start server.. all works perfectly.
I did all possible tests.  Check if your scenario is like me.
If you have some additional information, please post here, because I can't find any error.

**Comment by dmchandru** [comment] 2024-05-30 06:29
@gitdedc Did you scanned the QR code?

**Comment by gitdedc** [comment] 2024-05-31 13:56
Yes, normal.  Build, run (dev), read qr code -> Connected.
Stoped server, started server and returned as connected.

I understand what you are passing, the problem is simulate to find the error.

I deploy a new server to begin from zero, but all running perfectly (I always use AMD + Chrome, so I builded using ARM + Chromium, to environment change, but no errors found)

**Comment by jambazishvili** [comment] 2024-05-31 16:24
No the issue is not close. Thanks @gitdedc for the feedback & tests - I am facing the same issue. FYI @gitdedc @dmchandru we are facing the issue on Indian number. As we've been searching for the possible solutions / alternatives, we found out that other Indian based numbers have also the same problem w/ WA.

So, we are thinking that it is more WA related, rather than implementation itself. So, so far no solution, if something comes up, I'll update.

**Comment by dmchandru** [comment] 2024-06-03 10:47
@jambazishvili FYI: We have an on-premises server, It's working fine for all numbers. In AWS with same server spec. It's throwing the same error as you mentioned. I can also reproduce this issue in windows machine but not in MAC. Weird!

**Comment by gitdedc** [comment] 2024-06-03 12:54
@jambazishvili you are using Linux, aren't?

**Comment by akk-akk** [comment] 2024-06-07 16:03
I do face the same issue. 
On my Ubuntu based local environment, it works perfectly. 

But trying to connect with the server based in Mumbai, with an indian number, the above issue arises. 

@gitdedc @dmchandru @jambazishvili 
Thank you all for valuable feedbacks.

**Comment by adarshmadrecha** [comment] 2024-06-09 11:00
I also got same error.
my server - AWS EC2. `t3-medium` x84 architecture. `2 VCPU`, `4GB RAM`

```
verbose:  [adarsh:page] Page loaded
verbose:  [adarsh:client] Injecting wapi.js
debug:    [adarsh:client] Registering onStateChange event
error: 2024-06-09T10:54:15.009Z WAPI is not defined - Error: WAPI is not defined
    at /home/ubuntu/.yarn/berry/cache/@wppconnect-team-wppconnect-npm-1.30.3-1739879365-10c0.zip/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:107:31
    at step (/home/ubuntu/.yarn/berry/cache/@wppconnect-team-wppconnect-npm-1.30.3-1739879365-10c0.zip/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:49:23)
    at Object.next (/home/ubuntu/.yarn/berry/cache/@wppconnect-team-wppconnect-npm-1.30.3-1739879365-10c0.zip/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:30:53)
    at fulfilled (/home/ubuntu/.yarn/berry/cache/@wppconnect-team-wppconnect-npm-1.30.3-1739879365-10c0.zip/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:21:58)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at process.processImmediate (node:internal/timers:449:9)
JS Stack: ReferenceError: WAPI is not defined
    at pptr:evaluate;%2Fhome%2Fubuntu%2F.yarn%2Fberry%2Fcache%2F%40wppconnect-team-wppconnect-npm-1.30.3-1739879365-10c0.zip%2Fnode_modules%2F%40wppconnect-team%2Fwppconnect%2Fdist%2Fapi%2Fhelpers%2Fevaluate-and-return.js%3A99%3A56:56:47
    at pptr:evaluate;%2Fhome%2Fubuntu%2F.yarn%2Fberry%2Fcache%2F%40wppconnect-team-wppconnect-npm-1.30.3-1739879365-10c0.zip%2Fnode_modules%2F%40wppconnect-team%2Fwppconnect%2Fdist%2Fapi%2Fhelpers%2Fevaluate-and-return.js%3A99%3A56:56:77
    at new Promise (<anonymous>)
    at anonymous (pptr:evaluate;%2Fhome%2Fubuntu%2F.yarn%2Fberry%2Fcache%2F%40wppconnect-team-wppconnect-npm-1.30.3-1739879365-10c0.zip%2Fnode_modules%2F%40wppconnect-team%2Fwppconnect%2Fdist%2Fapi%2Fhelpers%2Fevaluate-and-return.js%3A99%3A56:54:14)
Function: function () { return WAPI.isConnected(); }

```

**Comment by icleitoncosta** [comment] 2024-06-10 02:08
Hello everyone, I made an update to the WAPI in the lib's repository (wppconnect), could you please test by updating?

`npm install @wppconnect-team/wppconnect@latest`

**Comment by adarshmadrecha** [comment] 2024-06-10 04:57
> Hello everyone, I made an update to the WAPI in the lib's repository (wppconnect), could you please test by updating?
> 
> `npm install @wppconnect-team/wppconnect@latest`

Not sure if the same issue or different. After following your instruction,

![image](https://github.com/wppconnect-team/wppconnect-server/assets/11911938/c5470edb-0a9a-4fc9-807c-60da794020c0)

![image](https://github.com/wppconnect-team/wppconnect-server/assets/11911938/5eb34638-182f-4d20-b69d-48699488cfdf)


Debug Info (this is shown when the server starts
![image](https://github.com/wppconnect-team/wppconnect-server/assets/11911938/d5ad1955-ced8-44ae-b876-1501faa71b96)

**Comment by icleitoncosta** [comment] 2024-06-10 10:51
Have you still been unable to connect, or was it just on the first attempt?

**Comment by icleitoncosta** [comment] 2024-06-13 00:03
Fixed by https://github.com/wppconnect-team/wppconnect-server/pull/1901

**Closed by icleitoncosta** 2024-06-13 00:03 UTC
Labels: bug, needs triage
